

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: org.shiloh.entity
# 应用服务 WEB 访问端口
server:
  port: 8080
spring:
  datasource:
    # 指定使用的数据库驱动，用到分库分表时，需要将驱动指定为 ShardingSphere 的
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # 指定使用的 Sharding Sphere 配置文件
    url: jdbc:shardingsphere:classpath:config.yml
